### ISSUE TITLE
Inference in command line fails

### ISSUE THREAD

**Issue by fazlicodes** [RupertLuo/Valley#14]
When I run the code:
`python3 valley/inference/run_valley.py --model-name ./weights/Valley2-7b/ --video-file ./test_videos/the_wait.mp4 --query "What is happening in this video?"`
I get the error:
`ValueError: You need to specify the <video> token in the query`

**Comment by RupertLuo** [comment]
The <video> token is a placeholder symbol for video. You need to write like this "What is happening in this video?\n<video>"

**Comment by fazlicodes** [comment]
Thanks it worked
