### ISSUE TITLE
light weight version of Valley

### ISSUE THREAD

**Issue by Xinxinatg** [RupertLuo/Valley#4]
Thanks for your wonderful work, I think this repo deserves much more attention than other gpt based video understanding, because this one generate the best output compared to other gpt-based video understanding tools according to my preliminary test. 

I am wondering whether there are light weight valley available that I can deploy on A30 server with 24 GB vram? I think the light weighted one will further broaden the user case.

**Comment by RupertLuo** [comment]
Thank you for your approval of this project. We are exploring on a smaller language model to achieve similar results. Currently, we are trying vicuna-7b and chatglm-6b. These two will be released soon and should be able to be used on a30 to deploy. In addition, we are also working on the quantization of 13b.

**Comment by Xinxinatg** [comment]
thanks for your prompt reply, looking forward to the update!

**Comment by ohmygoobness** [comment]
can this model be converted to 4-bit GPTQ

**Comment by RupertLuo** [comment]
> can this model be converted to 4-bit GPTQ

I haven't tried quantizing the weights yet.
