### ISSUE TITLE
prompt to generate instruction tuning data

### ISSUE THREAD

**Issue by ChaofanTao** [RupertLuo/Valley#5]
Hi, thank you for this interesting open-source work!

In your draft, you mention that ```we generate instruction tuning data by referring to the prompt motivated by LLaVA (Liu et al., 2023) and VideoChat (Li et al.,2023c), the prompt is shown in the appendix.```

However, I cannot find the appendix in public or the mentioned prompts in this code repo. I am appreciated it if you can provide these prompts.

**Comment by RupertLuo** [comment]
sure, here is our prompt.
![image](https://github.com/RupertLuo/Valley/assets/36270260/abe9dd04-0605-467e-a97e-e754ef8780cc)

**Comment by ChaofanTao** [comment]
Thanks! Additionally, I wonder what is the source of this picture, is there a link to the appendix?

**Comment by RupertLuo** [comment]
When we first uploaded our work to arxiv, we commented out the appendix, because there are some unfinished parts in the middle, and we will re-upload a version of the file with appendices to arxiv recently.

**Comment by ChaofanTao** [comment]
Got that! Thanks.
