### ISSUE TITLE
Release of pretrain weights

### ISSUE THREAD

**Issue by TonyXuQAQ** [RupertLuo/Valley#6]
Hi there, thanks for sharing the code and data. Will you release the pretrain weights so that we can directly fine tune the model? Thanks in advance.

**Comment by RupertLuo** [comment]
Sure, I will upload the pre-training weights of 13b and 7b **tomorrow**, and will give the complete data download steps (including videos). If I don't upload tomorrow, maybe I'm too busy and forget it, please remind me. 😆

**Comment by RupertLuo** [comment]
> 

Already upload.
