### ISSUE TITLE
Can I inference with Valley-13b by V100 GPUs?

### ISSUE THREAD

**Issue by TonyXuQAQ** [RupertLuo/Valley#9]
As you mentioned before, I can train Valley-13b by 16 V100 gpus with deepspeed zero3. I wonder whether I can infer with Valley-13b by V100. Does valley support multi-GPU inference?

**Comment by RupertLuo** [comment]
Yes，you need to set the device of model to 'auto' like this:
```python
model = ValleyLlamaForCausalLM.from_pretrained(model_name, torch_dtype=torch.float16, device_map='auto')
```

**Comment by TonyXuQAQ** [comment]
Thanks for the prompt reply!

**Comment by fightingaaa** [comment]
> Yes，you need to set the device of model to 'auto' like this:
> 
> ```python
> model = ValleyLlamaForCausalLM.from_pretrained(model_name, torch_dtype=torch.float16, device_map='auto')
> ```

hello,By setting the device of model to 'auto'  , the following error occurred. How to solve it? Thanks in advance
Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!
